# Generated by Django 4.0.2 on 2022-02-18 05:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя пациента')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия пациента')),
                ('login', models.CharField(max_length=16, verbose_name='Логин пациента')),
                ('password', models.CharField(max_length=16, verbose_name='Пароль пациента')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Пол')),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)], verbose_name='Возраст')),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(verbose_name='Текущая температура')),
                ('illumination', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1023), django.core.validators.MinValueValidator(0)], verbose_name='Освещённость')),
                ('fan', models.IntegerField(validators=[django.core.validators.MaxValueValidator(1023), django.core.validators.MinValueValidator(0)], verbose_name='Мощность вентилятора')),
                ('door', models.BooleanField(verbose_name='Дверь в комнате')),
                ('window', models.BooleanField(verbose_name='Окно в комнате')),
                ('patients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.patient', verbose_name='Пациенты в комнате')),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=32, verbose_name='Имя врача')),
                ('last_name', models.CharField(max_length=32, verbose_name='Фамилия врача')),
                ('login', models.CharField(max_length=16, verbose_name='Логин врача')),
                ('password', models.CharField(max_length=16, verbose_name='Пароль врача')),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='Пол')),
                ('age', models.IntegerField(validators=[django.core.validators.MaxValueValidator(200), django.core.validators.MinValueValidator(0)], verbose_name='Возраст')),
                ('patients', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.patient', verbose_name='Пациенты врача')),
            ],
        ),
    ]
