# Generated by Django 4.0.2 on 2022-02-18 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='email',
            field=models.EmailField(max_length=254, null=True, verbose_name='Почта врача'),
        ),
        migrations.AddField(
            model_name='room',
            name='is_present',
            field=models.BooleanField(null=True, verbose_name='Присутствие в комнате'),
        ),
    ]
