# Generated by Django 4.0.2 on 2022-02-19 03:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_analysis_alter_doctor_options_alter_patient_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='patients',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='analyzes',
        ),
        migrations.RemoveField(
            model_name='room',
            name='patients',
        ),
        migrations.AddField(
            model_name='analysis',
            name='patient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.patient', verbose_name='Пациент котрому принадлежит анализ'),
        ),
        migrations.AddField(
            model_name='patient',
            name='doctor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.doctor', verbose_name='Лечащий доктор'),
        ),
        migrations.AddField(
            model_name='patient',
            name='room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.room', verbose_name='Комната пациента'),
        ),
    ]
