# Generated by Django 4.0.2 on 2022-02-19 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_doctor_patients_remove_patient_analyzes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image_link',
            field=models.CharField(max_length=16, null=True, verbose_name='Ссылка на картинку врача'),
        ),
        migrations.AddField(
            model_name='patient',
            name='image_link',
            field=models.CharField(max_length=16, null=True, verbose_name='Ссылка на картинку пациента'),
        ),
    ]
