# Generated by Django 4.0.2 on 2022-02-19 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_doctor_image_link_patient_image_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='diagnosis',
            field=models.CharField(max_length=32, null=True, verbose_name='Заболевание пациента'),
        ),
    ]
