# Generated by Django 4.0.2 on 2022-02-19 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_patient_diagnosis'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='image_link',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Ссылка на картинку врача'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='image_link',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Ссылка на картинку пациента'),
        ),
    ]
