# Generated by Django 4.0.2 on 2022-02-19 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_doctor_age_alter_doctor_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='profession',
            field=models.CharField(max_length=16, null=True, verbose_name='Должность врача'),
        ),
    ]
