# Generated by Django 4.0.2 on 2022-02-19 20:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_doctor_profession'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='heater',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)], verbose_name='Нагреватель'),
        ),
        migrations.AddField(
            model_name='room',
            name='humidity',
            field=models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Уровень влажности'),
        ),
        migrations.AlterField(
            model_name='room',
            name='fan',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(255), django.core.validators.MinValueValidator(0)], verbose_name='Мощность вентилятора'),
        ),
    ]
